- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
- id: cargo-test
  name: cargo test
  description: Run tests
  entry: cargo test
  language: system
  types: [rust]
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
- id: leptos-build
  name: leptos build
  description: Run leptos build
  entry: cargo leptos test
  language: system
  types: [rust]
  pass_filenames: false
- id: leptos-test
  name: leptos test
  description: Run leptos test
  entry: cargo leptos test
  language: system
  types: [rust]
  pass_filenames: false
- id: leptos-e2e
  name: leptos end-to-end
  description: Run leptos e2e tests
  entry: cargo leptos end-to-end
  language: system
  types: [rust]
  pass_filenames: false
- id: leptos-e2e
  name: leptos end-to-end
  description: Run leptos e2e tests
  entry: cargo leptos end-to-end
  language: system
  types: [rust]
  pass_filenames: false
- id: leptosfmt
  name: leptosfmt
  description: Run leptosfmt
  entry: leptosfmt
  language: system
  args: ["--", "-r"]
  types: [rust]
  pass_filenames: true
